# Generated by Django 5.0.4 on 2024-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_historicalperformance_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperformance',
            name='response_time',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
